In [1]:
import pandas as pd

In [4]:
df_trades = pd.read_parquet("../../data/market_data/product=FDAX/year=2025/month=05/FDAX_20250502_trades.parquet")
df_orders = pd.read_parquet("../../data/market_data/product=FDAX/year=2025/month=05/FDAX_20250502_orders.parquet")

In [5]:
df_trades.head()

,ts_event,ts_in_delta,sequence,order_id,price,size,action,side,flags,channel_id,symbol
ts_recv,,,,,,,,,,,
1746144901156221954,1746144901156011554,4171,1894,0,22799000000000,7,T,N,0,15,FDAX SI 20250620 CS
1746144901158319610,1746144901158279161,2956,1917,1746144901158285749,22798000000000,1,T,A,0,15,FDAX SI 20250620 CS
1746144901158319610,1746144901158279161,2956,1917,10969516938011359680,22798000000000,1,F,B,0,15,FDAX SI 20250620 CS
1746144901168459902,1746144901168398709,2740,1927,1746144901168419175,22797000000000,1,T,A,0,15,FDAX SI 20250620 CS
1746144901168459902,1746144901168398709,2740,1927,10969516096969093850,22797000000000,1,F,B,0,15,FDAX SI 20250620 CS

In [6]:
df_orders.head(10)

,ts_event,ts_in_delta,sequence,order_id,price,size,action,side,flags,channel_id,symbol
ts_recv,,,,,,,,,,,
1746144901156221954,1746144901156011554,0,0,0,9223372036854775807,0,R,N,8,15,FDAX SI 20250620 CS
1746144901156221954,1746144000000000000,4171,1894,10969516096969093850,22797000000000,1,A,B,0,15,FDAX SI 20250620 CS
1746144901156221954,1746144000000000000,4171,1894,1746144005019085999,22800000000000,25,A,A,0,15,FDAX SI 20250620 CS
1746144901156221954,1746144000000000000,4171,1894,1746144900447399014,22800000000000,1,A,A,0,15,FDAX SI 20250620 CS
1746144901156221954,1746144000000000000,4171,1894,10969516096969100820,22790000000000,1,A,B,0,15,FDAX SI 20250620 CS
1746144901156221954,1746144000000000000,4171,1894,1746144877272787477,22829000000000,1,A,A,0,15,FDAX SI 20250620 CS
1746144901156221954,1746144000000000000,4171,1894,10969516096970073683,22788000000000,1,A,B,0,15,FDAX SI 20250620 CS
1746144901156221954,1746144000000000000,4171,1894,1746026693032925613,22833000000000,10,A,A,0,15,FDAX SI 20250620 CS
1746144901156221954,1746144000000000000,4171,1894,10969516096969106338,22783000000000,1,A,B,0,15,FDAX SI 20250620 CS
1746144901156221954,1746144000000000000,4171,1894,1746144319411230777,22850000000000,1,A,A,0,15,FDAX SI 20250620 CS

In [7]:
df_trades.shape

(64409, 11)

In [8]:
df_orders.shape

(3139205, 11)

In [9]:
df_orders[df_orders.price < 0]

,ts_event,ts_in_delta,sequence,order_id,price,size,action,side,flags,channel_id,symbol
ts_recv,,,,,,,,,,,
1746144901156267625,1746144000000000000,4511,1901,10969414030151988095,-128500000000,1,A,B,0,15,FDAX.S.JUN25.SEP25.SPD
1746144901156267625,1746144000000000000,4511,1901,1746042065785292234,-116500000000,1,A,A,0,15,FDAX.S.JUN25.SEP25.SPD
1746144901156267625,1746144000000000000,4511,1901,10969414030152065407,-129000000000,1,A,B,0,15,FDAX.S.JUN25.SEP25.SPD
1746144901156267625,1746144000000000000,4511,1901,1745922277209762843,-113500000000,1,A,A,0,15,FDAX.S.JUN25.SEP25.SPD
1746144901156273469,1746144000000000000,4764,1902,10969393674160514046,-129500000000,1,A,B,0,15,FDAX.S.JUN25.SEP25.SPD
...,...,...,...,...,...,...,...,...,...,...,...
1746215431871960144,1746215431871934415,2043,3041630,1746215431871942388,-108000000000,1,A,A,128,15,FDAX.S.JUN25.SEP25.SPD
1746215980569009642,1746215980568984145,2523,3061954,1746215431871942388,-108000000000,1,C,A,128,15,FDAX.S.JUN25.SEP25.SPD
1746215980574218782,1746215980574191455,2053,3061955,1746215980574200811,-104000000000,1,A,A,128,15,FDAX.S.JUN25.SEP25.SPD
1746215995078288869,1746215995078270459,1810,3062538,1746215980574200811,-104000000000,1,C,A,128,15,FDAX.S.JUN25.SEP25.SPD
1746215995080281099,1746215995080266925,1811,3062539,10969583946609313465,-150000000000,1,C,B,128,15,FDAX.S.JUN25.SEP25.SPD

In [12]:
df_orders.sort_values("price").head()

,ts_event,ts_in_delta,sequence,order_id,price,size,action,side,flags,channel_id,symbol
ts_recv,,,,,,,,,,,
1746144901156276948,1746144000000000000,3633,1903,10966173223568376777,-508500000000,1,A,B,128,15,FDAX.S.JUN25.SEP25.SPD
1746165600905341644,1746165600905322229,2464,161487,10969537637760104246,-464500000000,1,A,B,128,15,FDAX.S.JUN25.DEC25.SPD
1746165600642135651,1746165600642113823,1947,161410,10969537637496895467,-461000000000,1,A,B,128,15,FDAX.S.JUN25.DEC25.SPD
1746144901156276948,1746144000000000000,3633,1903,10967670855524570262,-317500000000,1,A,B,0,15,FDAX.S.JUN25.SEP25.SPD
1746144901156276948,1746144000000000000,3633,1903,10967670855755081811,-307500000000,1,A,B,0,15,FDAX.S.JUN25.SEP25.SPD

In [13]:
df_orders.value_counts("flags")

flags
128    3055866
0        83332
8            7
Name: count, dtype: int64